spring.datasource.url=jdbc:mysql://localhost:3306/subscriptiondb
spring.datasource.username=root
spring.datasource.password=haritha@2806

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
